services:

  wp-db:
    image: postgres:17
    container_name: wp2024_events
    environment:
      POSTGRES_USER: wp
      POSTGRES_PASSWORD: wp123
      POSTGRES_DB: events
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: event-app
    depends_on:
      - wp-db
    ports:
      - "9091:9091"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://wp-db:5432/events
      SPRING_DATASOURCE_USERNAME: wp
      SPRING_DATASOURCE_PASSWORD: wp123
      SPRING_PROFILES_ACTIVE: prod
    restart: unless-stopped
