---
apiVersion: v1
kind: Secret
metadata:
  name: events-db-secrets
  namespace: events-namespace
type: Opaque
stringData:
  POSTGRES_USER: wp
  POSTGRES_PASSWORD: wp123
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: events-db-config
  namespace: events-namespace
data:
  POSTGRES_DB: events
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: events-db
  namespace: events-namespace
spec:
  serviceName: "events-db"
  replicas: 1
  selector:
    matchLabels:
      app: events-db
  template:
    metadata:
      labels:
        app: events-db
    spec:
      containers:
      - name: postgres
        image: postgres:17
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: events-db-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: events-db-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: events-db-config
              key: POSTGRES_DB
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: events-db
  namespace: events-namespace
spec:
  ports:
  - port: 5432
  clusterIP: None
  selector:
    app: events-db

