--
-- PostgreSQL database dump
--

\restrict PLSBN6SZqvtzIhe2I0bYw91BFBs7GN2RtmOz1DPToJ6pVxSUNrEeTKcVTFm31UU

-- Dumped from database version 17.6 (Debian 17.6-1.pgdg13+1)
-- Dumped by pg_dump version 17.6 (Debian 17.6-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: event; Type: TABLE; Schema: public; Owner: wp
--

CREATE TABLE public.event (
    id bigint NOT NULL,
    date date,
    description character varying(255),
    name character varying(255),
    popularity_score double precision NOT NULL,
    location_id bigint
);


ALTER TABLE public.event OWNER TO wp;

--
-- Name: event_id_seq; Type: SEQUENCE; Schema: public; Owner: wp
--

ALTER TABLE public.event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event_location; Type: TABLE; Schema: public; Owner: wp
--

CREATE TABLE public.event_location (
    id bigint NOT NULL,
    address character varying(255),
    capacity character varying(255),
    description character varying(255),
    name character varying(255)
);


ALTER TABLE public.event_location OWNER TO wp;

--
-- Name: event_location_id_seq; Type: SEQUENCE; Schema: public; Owner: wp
--

ALTER TABLE public.event_location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_users; Type: TABLE; Schema: public; Owner: wp
--

CREATE TABLE public.shop_users (
    username character varying(255) NOT NULL,
    is_account_non_expired boolean NOT NULL,
    is_account_non_locked boolean NOT NULL,
    is_credentials_non_expired boolean NOT NULL,
    is_enabled boolean NOT NULL,
    name character varying(255),
    password character varying(255),
    role character varying(255),
    surname character varying(255),
    CONSTRAINT shop_users_role_check CHECK (((role)::text = ANY ((ARRAY['ROLE_USER'::character varying, 'ROLE_ADMIN'::character varying])::text[])))
);


ALTER TABLE public.shop_users OWNER TO wp;

--
-- Data for Name: event; Type: TABLE DATA; Schema: public; Owner: wp
--

COPY public.event (id, date, description, name, popularity_score, location_id) FROM stdin;
4	2025-11-15	Annual international jazz festival featuring renowned artists from around the world, with live performances and workshops for music enthusiasts.	Skopje Jazz Festival 2025	9	1
5	2025-10-05	A series of classical music concerts performed by the Macedonian Philharmonic Orchestra, highlighting both local and international compositions.	Classical Evenings at Philharmonic	8	2
7	2025-08-20	Outdoor music festival featuring popular bands and solo performers in a lively park setting, perfect for families and young audiences.	Summer Open-Air Concert	7	16
8	2025-09-10	Interactive exhibition presenting the rich history and cultural heritage of Macedonia, including artifacts, multimedia presentations, and guided tours.	Historical Exhibition: Macedonia Through Ages	8	4
9	2025-09-25	Annual drama festival showcasing performances by local and international theater troupes, with workshops and discussions on contemporary theater.	Bitola Theatre Festival	9	5
10	2025-07-15	Open-air classical music performances held at the historic Ohrid amphitheater, providing a unique combination of music and scenic views.	Ohrid Summer Classics	10	6
11	2025-08-05	Outdoor film screenings and cultural events during the summer season, promoting international cinema and local artistic productions.	Ohrid Film Nights	7	7
12	2025-09-18	Week-long event featuring art exhibitions, workshops, and performances, showcasing contemporary art and fostering community engagement.	Strumica Art Week	8	9
13	2025-09-20	Special screenings of classic and contemporary films, accompanied by discussions and presentations on cinematic arts.	Cinema Classics Night	7	10
14	2025-09-30	Launch of the autumn theater season featuring plays, ballet, and opera performances, highlighting both Macedonian and international talent.	National Theatre Autumn Season	9	11
15	2025-10-07	Exhibition presenting contemporary works by local and international artists, along with workshops and networking sessions for creatives.	Tetovo Contemporary Art Exhibition	7	12
16	2025-09-05	Series of classical music concerts held in the historic Roman amphitheater, offering a unique cultural experience in an ancient setting.	Stobi Classical Evenings	8	13
17	2025-09-15	Cultural evening featuring music, dance, and art exhibitions, highlighting local talent and fostering community participation.	Gostivar Cultural Night	7	14
18	2025-08-25	Festival combining film screenings with live music performances, celebrating local culture and international artistic contributions.	Drim Film & Music Festival	8	15
19	2025-08-18	Open-air cinema event by the lake, showcasing acclaimed international and Macedonian films. Includes audience discussions and a pre-screening cultural introduction.	Lakefront Film Screening	7	7
20	2025-07-22	Celebrating the rich folk traditions of the Balkans, this festival features live performances, folk dance demonstrations, and cultural storytelling sessions.	Balkan Folk Music Festival	9	7
\.


--
-- Data for Name: event_location; Type: TABLE DATA; Schema: public; Owner: wp
--

COPY public.event_location (id, address, capacity, description, name) FROM stdin;
1	Bul. Kliment Ohridski 38, Skopje	1200	The Macedonian Cultural Center (MKSC) is the premier venue for cultural events, concerts, and exhibitions in Skopje, featuring modern facilities and multiple halls suitable for large audiences.	MKSC Skopje
2	Blvd. Goce Delčev 28, Skopje	800	The Macedonian Philharmonic Hall hosts classical music concerts, orchestral performances, and cultural gatherings, providing a refined atmosphere for music enthusiasts.	Macedonian Philharmonic
4	Blvd. Krste Misirkov 2, Skopje	300	The national museum showcases Macedonian history, art, and cultural heritage, hosting exhibitions, educational programs, and occasional cultural events.	Museum of Macedonia
5	Krste Misirkov 14, Bitola	600	A prominent theater venue in Bitola, offering dramatic performances, plays, and local festivals, known for supporting both traditional and contemporary performing arts.	Bitola Drama Theatre
6	Samoilova 1, Ohrid	1000	Historic open-air theater in Ohrid, hosting classical and modern performances, summer festivals, and cultural events with breathtaking views of Lake Ohrid.	Ohrid Old Theatre
7	Ljubomir Taseski 5, Ohrid	1500	Seasonal outdoor stage designed for music concerts, theatrical performances, and film screenings, providing a lively setting for summer cultural experiences.	Ohrid Summer Stage
9	Dimitar Vlahov 22, Strumica	400	Dedicated gallery and performance venue for visual and performing arts, hosting exhibitions, theater productions, and creative workshops for all ages.	Art Center Strumica
10	Blvd. Ilinden 55, Veles	350	Historic cinema and stage offering film screenings, theatrical performances, and cultural programs, fostering a rich cultural experience for the local community.	Cinema Theater Kultura
11	Blvd. Krste Misirkov 10, Skopje	900	Iconic national theater presenting a wide range of classical and modern plays, ballet, and operas, recognized for its artistic excellence and cultural impact.	National Theatre Skopje
12	Blvd. Ilinden 20, Tetovo	250	Contemporary art gallery showcasing works from local and international artists, hosting exhibitions, workshops, and cultural networking events.	City Gallery Tetovo
13	Stobi Archaeological Site, Gradsko	2000	Ancient Roman amphitheater used for classical music concerts, theatrical performances, and cultural heritage events in a historical open-air setting.	Stobi Amphitheater
14	Blvd. Goce Delčev 40, Gostivar	500	Hub for arts and culture offering concerts, exhibitions, and community programs, encouraging local talent and cultural exchange.	Cultural Center Gostivar
15	Blvd. Drim 12, Struga	300	Modern cinema and event hall used for film screenings, music performances, and cultural festivals, serving as a key venue in Struga.	Drim Cinema Hall
16	Blvd. Partizanski Odredi, Skopje	5000	A spacious urban park ideal for outdoor cultural events, open-air concerts, festivals, and recreational activities, offering a vibrant environment in the heart of the city.	City Park Skopje
\.


--
-- Data for Name: shop_users; Type: TABLE DATA; Schema: public; Owner: wp
--

COPY public.shop_users (username, is_account_non_expired, is_account_non_locked, is_credentials_non_expired, is_enabled, name, password, role, surname) FROM stdin;
angela.nikolovska	t	t	t	t	Angela	$2a$10$Q7HHZgja1tMetSX1YglQPOfxsaeO2Ynb6GcUTujZe9oSMLehLCGYW	ROLE_USER	Nikolovska
admin	t	t	t	t	admin	$2a$10$WPGU96ea/ep.rsodNo1drOb5eyudUYuvjODsnou1n4UXQ4EfH5n3a	ROLE_ADMIN	
\.


--
-- Name: event_id_seq; Type: SEQUENCE SET; Schema: public; Owner: wp
--

SELECT pg_catalog.setval('public.event_id_seq', 20, true);


--
-- Name: event_location_id_seq; Type: SEQUENCE SET; Schema: public; Owner: wp
--

SELECT pg_catalog.setval('public.event_location_id_seq', 16, true);


--
-- Name: event_location event_location_pkey; Type: CONSTRAINT; Schema: public; Owner: wp
--

ALTER TABLE ONLY public.event_location
    ADD CONSTRAINT event_location_pkey PRIMARY KEY (id);


--
-- Name: event event_pkey; Type: CONSTRAINT; Schema: public; Owner: wp
--

ALTER TABLE ONLY public.event
    ADD CONSTRAINT event_pkey PRIMARY KEY (id);


--
-- Name: shop_users shop_users_pkey; Type: CONSTRAINT; Schema: public; Owner: wp
--

ALTER TABLE ONLY public.shop_users
    ADD CONSTRAINT shop_users_pkey PRIMARY KEY (username);


--
-- Name: event fk1cvm1eskmpxiwnb3t43hsurrp; Type: FK CONSTRAINT; Schema: public; Owner: wp
--

ALTER TABLE ONLY public.event
    ADD CONSTRAINT fk1cvm1eskmpxiwnb3t43hsurrp FOREIGN KEY (location_id) REFERENCES public.event_location(id);


--
-- PostgreSQL database dump complete
--

\unrestrict PLSBN6SZqvtzIhe2I0bYw91BFBs7GN2RtmOz1DPToJ6pVxSUNrEeTKcVTFm31UU

