--
-- PostgreSQL database dump
--

\restrict VwPZ5V1rRXiszXkAAJPJmMVWThgK1HyDTyhDdCQBLdSp4H2pVtgzpIdtRf905n5

-- Dumped from database version 17.6 (Debian 17.6-1.pgdg13+1)
-- Dumped by pg_dump version 17.6 (Debian 17.6-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: event; Type: TABLE; Schema: public; Owner: wp
--

CREATE TABLE public.event (
    id bigint NOT NULL,
    date date,
    description character varying(255),
    name character varying(255),
    popularity_score double precision NOT NULL,
    location_id bigint
);


ALTER TABLE public.event OWNER TO wp;

--
-- Name: event_id_seq; Type: SEQUENCE; Schema: public; Owner: wp
--

ALTER TABLE public.event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event_location; Type: TABLE; Schema: public; Owner: wp
--

CREATE TABLE public.event_location (
    id bigint NOT NULL,
    address character varying(255),
    capacity character varying(255),
    description character varying(255),
    name character varying(255)
);


ALTER TABLE public.event_location OWNER TO wp;

--
-- Name: event_location_id_seq; Type: SEQUENCE; Schema: public; Owner: wp
--

ALTER TABLE public.event_location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_users; Type: TABLE; Schema: public; Owner: wp
--

CREATE TABLE public.shop_users (
    username character varying(255) NOT NULL,
    is_account_non_expired boolean NOT NULL,
    is_account_non_locked boolean NOT NULL,
    is_credentials_non_expired boolean NOT NULL,
    is_enabled boolean NOT NULL,
    name character varying(255),
    password character varying(255),
    role character varying(255),
    surname character varying(255),
    CONSTRAINT shop_users_role_check CHECK (((role)::text = ANY ((ARRAY['ROLE_USER'::character varying, 'ROLE_ADMIN'::character varying])::text[])))
);


ALTER TABLE public.shop_users OWNER TO wp;

--
-- Data for Name: event; Type: TABLE DATA; Schema: public; Owner: wp
--

COPY public.event (id, date, description, name, popularity_score, location_id) FROM stdin;
\.


--
-- Data for Name: event_location; Type: TABLE DATA; Schema: public; Owner: wp
--

COPY public.event_location (id, address, capacity, description, name) FROM stdin;
\.


--
-- Data for Name: shop_users; Type: TABLE DATA; Schema: public; Owner: wp
--

COPY public.shop_users (username, is_account_non_expired, is_account_non_locked, is_credentials_non_expired, is_enabled, name, password, role, surname) FROM stdin;
\.


--
-- Name: event_id_seq; Type: SEQUENCE SET; Schema: public; Owner: wp
--

SELECT pg_catalog.setval('public.event_id_seq', 1, false);


--
-- Name: event_location_id_seq; Type: SEQUENCE SET; Schema: public; Owner: wp
--

SELECT pg_catalog.setval('public.event_location_id_seq', 1, false);


--
-- Name: event_location event_location_pkey; Type: CONSTRAINT; Schema: public; Owner: wp
--

ALTER TABLE ONLY public.event_location
    ADD CONSTRAINT event_location_pkey PRIMARY KEY (id);


--
-- Name: event event_pkey; Type: CONSTRAINT; Schema: public; Owner: wp
--

ALTER TABLE ONLY public.event
    ADD CONSTRAINT event_pkey PRIMARY KEY (id);


--
-- Name: shop_users shop_users_pkey; Type: CONSTRAINT; Schema: public; Owner: wp
--

ALTER TABLE ONLY public.shop_users
    ADD CONSTRAINT shop_users_pkey PRIMARY KEY (username);


--
-- Name: event fk1cvm1eskmpxiwnb3t43hsurrp; Type: FK CONSTRAINT; Schema: public; Owner: wp
--

ALTER TABLE ONLY public.event
    ADD CONSTRAINT fk1cvm1eskmpxiwnb3t43hsurrp FOREIGN KEY (location_id) REFERENCES public.event_location(id);


--
-- PostgreSQL database dump complete
--

\unrestrict VwPZ5V1rRXiszXkAAJPJmMVWThgK1HyDTyhDdCQBLdSp4H2pVtgzpIdtRf905n5

